twig:
    default_path: '%kernel.project_dir%/templates'
    #L'option 'Form_themes' vous permet de renseigner un layout général pour les form
    #form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
